### PR TITLE
Sam4l support

### PR DESCRIPTION
**Pull request by danielinux**

### CODE REVIEW

**Comment by brabo** [comment]
@maksymko :+1:
We just have to fix the conflicts we have and then we merge this into our branch.
Thanks! Nice work!!

**Comment by danielinux** [comment]
Manually merged! Thanks @maksymko :+1:

**Comment by maksymko** [comment]
@danielinux, thanks for taking care of this!

**Comment by danielinux** [comment]
@maksymko no problem. Let us know if you have other branches you are working on and you wanted to see merged onto our branch/fork.

**Comment by maksymko** [comment]
Hey Daniele,

what is the relationship between your repo and the main (Karl's) branch?
Are you maintaining this as a separate branch? Do you submit changes
upstream?

On Sun, Jun 26, 2016 at 10:01 AM, Daniele Lacamera <notifications@github.com

> wrote:
> 
> @maksymko https://github.com/maksymko no problem. Let us know if you
> have other branches you are working on and you wanted to see merged onto
> our branch/fork.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/insane-adding-machines/libopencm3/pull/13#issuecomment-228611036,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABf658OVcokQ4WEsP3HZyCnacAW0FNdUks5qPrCBgaJpZM4I-lya
> .

## 

## 

Maxim Sloyko

**Comment by brabo** [comment]
@maksymko This repository was maintained as a seperate branch of libopencm3 as we need a faster rate than libopencm3 has atm. We decided to make it into a proper fork of libopencm3 named [unicore-mx](https://github.com/insane-adding-machines/unicore-mx) with the goals of:
- Faster commit/merge rate
- Unified and stable API

We will not make an effort to share upstream anymore. In the past we have tried, only to see PRs getting ignored, or even okayed and subsequently stay unmerged. We will however keep merging in any new stuff from libopencm3. So @maksymko, hopefully we can look forward to a PR from you! ;)

**Comment by maksymko** [comment]
@brabo,

That's what I kind of suspected :)

Glad to hear that somebody doing this. I'll try to migrate my stuff over to
unicore-mx, I have support for nRF51
https://www.nordicsemi.com/eng/Products/nRF51-Series-SoC part in the
pipeline, hopefully will be able to send it for review this month.

On Thu, Jul 14, 2016 at 4:19 AM, brabo notifications@github.com wrote:

> @maksymko https://github.com/maksymko This repository was maintained as
> a seperate branch of libopencm3 as we need a faster rate than libopencm3
> has atm. We decided to make it into a proper fork of libopencm3 named
> unicore-mx https://github.com/insane-adding-machines/unicore-mx with
> the goals of:
> - ## Faster commit/merge rate
>   
>   Unified and stable API
>   
>   We will not make an effort to share upstream anymore. In the past we
>   have tried, only to see PRs getting ignored, or even okayed and
>   subsequently stay unmerged. We will however keep merging in any new stuff
>   from libopencm3. So @maksymko https://github.com/maksymko, hopefully
>   we can look forward to a PR from you! ;)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/insane-adding-machines/libopencm3/pull/13#issuecomment-232637391,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABf65-fUlopS9XkxZPIByd3HfnaU0ahOks5qVhtVgaJpZM4I-lya
> .

## 

## 

Maxim Sloyko

**Comment by brabo** [comment]
@maksymko Oh nice! We're looking forward to it! :)

**Pull request merged**
